### ISSUE TITLE
Error running horse collapose

### ISSUE THREAD

**Issue by yuyao1997** [mukailab/ssdr#1]
Hi,

I just found that when I try to run horse collapose using Microsoft 2016, it always gives me an error saying that abort() has been called. It will break at the if statement from line 236 to line 240.

Would you like to help me with this problem?

Thank you!

**Comment by TomohikoMukai** [comment]
Hi,

Sorry for the silence and thank you for the feedback.

Although I haven't carried out an experiment on the horse collapse data yet, I wonder how many bones you are trying to use.
The error occurs regardless of the number of bones?

I will locate the problem and I would appreciate your further assistance.

Best,

Tomo

**Comment by yuyao1997** [comment]
Hi,

Thank you for your response. I've tried 16, some numbers below and some numbers larger than that. It always gave me the same error. 

Is there any problem with the number that I've used?

Thank you!

Best regards,
Yuyao

**Comment by TomohikoMukai** [comment]
Hi,

Thank you, I'll try to figure out the solution.

> Is there any problem with the number that I've used?
> 
> In my experiments, the quadratic programming solver sometimes became unstable especially when I used many bones. It might be a bug of my code, but I am not sure at this moment.

Best,
Tomo

**Comment by TomohikoMukai** [comment]
Hi Yuyao,

The runtime error doesn't happen in my VS2013 environment.
It seems to me that the error is caused by a failure of obj file loading.

Can you make sure the correct filename is specified in your code (line 317--318 at HorseObject::OnInit) or
can you try following code after unzip https://people.csail.mit.edu/sumner/research/deftransfer/data/horse-collapse.zip to 'data2' folder?

`
    LoadModel(device, L"./data2/horse-collapose-reference.obj", XMFLOAT4A(0.5f, 0.5f, 0.5f, 1.0f));
    LoadAnim(L"./data2/horse-collapose-%02d.obj");
`

Best,

Tomo
